[tokio]
threads = '$TOKIO_THREADS'

[jupiter_candle]
active = '$JUPITER_CANDLE_ACTIVE'
connection_string = '$JUPITER_CANDLE_POSTGRES_CONNECTION_STRING'
pool_min = '$JUPITER_CANDLE_POSTGRES_POOL_MIN'
pool_max = '$JUPITER_CANDLE_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$JUPITER_CANDLE_POSTGRES_TIMEOUT_ACQUIRE_MS'

[jupiter_mcap]
active = '$JUPITER_MCAP_ACTIVE'
connection_string = '$JUPITER_MCAP_POSTGRES_CONNECTION_STRING'
pool_min = '$JUPITER_MCAP_POSTGRES_POOL_MIN'
pool_max = '$JUPITER_MCAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$JUPITER_MCAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[jupiter_twap]
active = '$JUPITER_TWAP_ACTIVE'
connection_string = '$JUPITER_TWAP_POSTGRES_CONNECTION_STRING'
pool_min = '$JUPITER_TWAP_POSTGRES_POOL_MIN'
pool_max = '$JUPITER_TWAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$JUPITER_TWAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[jupiter_usd]
active = '$JUPITER_USD_ACTIVE'
connection_string = '$JUPITER_USD_POSTGRES_CONNECTION_STRING'
pool_min = '$JUPITER_USD_POSTGRES_POOL_MIN'
pool_max = '$JUPITER_USD_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$JUPITER_USD_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpfun_candle]
active = '$PUMPFUN_CANDLE_ACTIVE'
connection_string = '$PUMPFUN_CANDLE_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPFUN_CANDLE_POSTGRES_POOL_MIN'
pool_max = '$PUMPFUN_CANDLE_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPFUN_CANDLE_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpfun_mcap]
active = '$PUMPFUN_MCAP_ACTIVE'
connection_string = '$PUMPFUN_MCAP_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPFUN_MCAP_POSTGRES_POOL_MIN'
pool_max = '$PUMPFUN_MCAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPFUN_MCAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpfun_progress]
active = '$PUMPFUN_PROGRESS_ACTIVE'
connection_string = '$PUMPFUN_PROGRESS_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPFUN_PROGRESS_POSTGRES_POOL_MIN'
pool_max = '$PUMPFUN_PROGRESS_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPFUN_PROGRESS_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpfun_summary]
active = '$PUMPFUN_SUMMARY_ACTIVE'
connection_string = '$PUMPFUN_SUMMARY_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPFUN_SUMMARY_POSTGRES_POOL_MIN'
pool_max = '$PUMPFUN_SUMMARY_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPFUN_SUMMARY_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpfun_twap]
active = '$PUMPFUN_TWAP_ACTIVE'
connection_string = '$PUMPFUN_TWAP_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPFUN_TWAP_POSTGRES_POOL_MIN'
pool_max = '$PUMPFUN_TWAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPFUN_TWAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpfun_usd]
active = '$PUMPFUN_USD_ACTIVE'
connection_string = '$PUMPFUN_USD_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPFUN_USD_POSTGRES_POOL_MIN'
pool_max = '$PUMPFUN_USD_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPFUN_USD_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpswap_candle]
active = '$PUMPSWAP_CANDLE_ACTIVE'
connection_string = '$PUMPSWAP_CANDLE_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPSWAP_CANDLE_POSTGRES_POOL_MIN'
pool_max = '$PUMPSWAP_CANDLE_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPSWAP_CANDLE_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpswap_mcap]
active = '$PUMPSWAP_MCAP_ACTIVE'
connection_string = '$PUMPSWAP_MCAP_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPSWAP_MCAP_POSTGRES_POOL_MIN'
pool_max = '$PUMPSWAP_MCAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPSWAP_MCAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpswap_summary]
active = '$PUMPSWAP_SUMMARY_ACTIVE'
connection_string = '$PUMPSWAP_SUMMARY_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPSWAP_SUMMARY_POSTGRES_POOL_MIN'
pool_max = '$PUMPSWAP_SUMMARY_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPSWAP_SUMMARY_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpswap_twap]
active = '$PUMPSWAP_TWAP_ACTIVE'
connection_string = '$PUMPSWAP_TWAP_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPSWAP_TWAP_POSTGRES_POOL_MIN'
pool_max = '$PUMPSWAP_TWAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPSWAP_TWAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpswap_usd]
active = '$PUMPSWAP_USD_ACTIVE'
connection_string = '$PUMPSWAP_USD_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPSWAP_USD_POSTGRES_POOL_MIN'
pool_max = '$PUMPSWAP_USD_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPSWAP_USD_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpup_candle]
active = '$PUMPUP_CANDLE_ACTIVE'
connection_string = '$PUMPUP_CANDLE_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPUP_CANDLE_POSTGRES_POOL_MIN'
pool_max = '$PUMPUP_CANDLE_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPUP_CANDLE_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpup_mcap]
active = '$PUMPUP_MCAP_ACTIVE'
connection_string = '$PUMPUP_MCAP_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPUP_MCAP_POSTGRES_POOL_MIN'
pool_max = '$PUMPUP_MCAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPUP_MCAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpup_progress]
active = '$PUMPUP_PROGRESS_ACTIVE'
connection_string = '$PUMPUP_PROGRESS_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPUP_PROGRESS_POSTGRES_POOL_MIN'
pool_max = '$PUMPUP_PROGRESS_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPUP_PROGRESS_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpup_summary]
active = '$PUMPUP_SUMMARY_ACTIVE'
connection_string = '$PUMPUP_SUMMARY_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPUP_SUMMARY_POSTGRES_POOL_MIN'
pool_max = '$PUMPUP_SUMMARY_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPUP_SUMMARY_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpup_twap]
active = '$PUMPUP_TWAP_ACTIVE'
connection_string = '$PUMPUP_TWAP_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPUP_TWAP_POSTGRES_POOL_MIN'
pool_max = '$PUMPUP_TWAP_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPUP_TWAP_POSTGRES_TIMEOUT_ACQUIRE_MS'

[pumpup_usd]
active = '$PUMPUP_USD_ACTIVE'
connection_string = '$PUMPUP_USD_POSTGRES_CONNECTION_STRING'
pool_min = '$PUMPUP_USD_POSTGRES_POOL_MIN'
pool_max = '$PUMPUP_USD_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$PUMPUP_USD_POSTGRES_TIMEOUT_ACQUIRE_MS'

[solana_sol]
active = '$SOLANA_SOL_ACTIVE'
connection_string = '$SOLANA_SOL_POSTGRES_CONNECTION_STRING'
pool_min = '$SOLANA_SOL_POSTGRES_POOL_MIN'
pool_max = '$SOLANA_SOL_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$SOLANA_SOL_POSTGRES_TIMEOUT_ACQUIRE_MS'

[leaderboard]
active = '$LEADERBOARD_ACTIVE'
connection_string = '$LEADERBOARD_POSTGRES_CONNECTION_STRING'
pool_min = '$LEADERBOARD_POSTGRES_POOL_MIN'
pool_max = '$LEADERBOARD_POSTGRES_POOL_MAX'
timeout_acquire_ms = '$LEADERBOARD_POSTGRES_TIMEOUT_ACQUIRE_MS'