[package]
name = "engine"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../../crates/base" }
common = { path = "../../crates/common" }
solana = { path = "../../crates/solana" }

async-trait = { workspace = true }
bigdecimal = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

log = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }

tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
dotenv = { workspace = true }
serde_json = { workspace = true }
test-log = { workspace = true }
tokio = { workspace = true }